import Header from '@/components/layout/header';
import Sidebar from '@/components/layout/sidebar';
import '@/styles/globals.css';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <Sidebar />
        {/* {children} */}
      </body>
    </html>
  );
}
